import { X } from 'lucide-react';
import type { UserFieldErrors, UserFormState } from '../types';
import { ROLE_BITS } from '../types';
import { SearchableSelect } from '../../../../components/ui/SearchableSelect';

type Props = { open: boolean; isEdit: boolean; form: UserFormState; errors: UserFieldErrors; submitting: boolean; canSetDirector: boolean; setField: <K extends keyof UserFormState>(key: K, value: UserFormState[K]) => void; onClose: () => void; onSubmit: () => void };

export default function AddEditUserDialog({ open, isEdit, form, errors, submitting, canSetDirector, setField, onClose, onSubmit }: Props) {
  if (!open) return null;
  const roleMask = Number(form.role_mask) || 0;
  const selectedRoles = ROLE_BITS.filter(role => (roleMask & role.value) !== 0);
  const roleOptions = ROLE_BITS.filter(role => (roleMask & role.value) === 0 && (role.value !== 64 || canSetDirector)).map(role => ({ value: String(role.value), label: role.label }));
  const addRole = (value: string) => { const bit = Number(value); if (bit) setField('role_mask', String(roleMask + bit)); };
  const removeRole = (bit: number) => { if (bit === 64 && !canSetDirector) return; setField('role_mask', String(roleMask - bit)); };
  return <div className="fixed inset-0 z-[9999] flex justify-end"><button type="button" aria-label="Đóng" className="fixed inset-0 bg-black/40 backdrop-blur-md animate-in fade-in duration-200" onClick={onClose} /><div className="relative flex h-screen w-full max-w-[680px] flex-col border-l border-border bg-[#f8fafc] shadow-2xl dialog-slide-in"><div className="flex items-center justify-between border-b border-border bg-white px-6 py-4"><h2 className="text-[16px] font-extrabold text-foreground">{isEdit ? 'Sửa nhân sự' : 'Thêm nhân sự'}</h2><button onClick={onClose} className="rounded-full p-2 hover:bg-muted"><X size={18} /></button></div><div className="flex-1 overflow-y-auto p-6 custom-scrollbar"><div className="grid gap-4"><Field label="Username" value={form.username} error={errors.username} onChange={v => setField('username', v)} /><Field label="Họ tên" value={form.name} error={errors.name} onChange={v => setField('name', v)} /><Field label="Điện thoại" value={form.phone} error={errors.phone} onChange={v => setField('phone', v)} /><div className="rounded-2xl border border-border bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><div className="text-[13px] font-extrabold text-foreground">Chọn quyền</div><div className="text-[12px] font-medium text-muted-foreground">Role mask tự tính theo tổng bit RBAC.</div></div><span className="rounded-full bg-primary/10 px-2 py-1 text-[11px] font-extrabold text-primary">{roleMask}</span></div><SearchableSelect value="" options={roleOptions} onValueChange={addRole} placeholder="Chọn quyền" searchPlaceholder="Tìm quyền..." emptyMessage="Đã chọn tất cả quyền khả dụng." className="h-11 bg-white font-bold text-foreground" />{errors.role_mask && <div className="mt-2 text-[12px] font-medium text-red-500">{errors.role_mask}</div>}<div className="mt-3 flex flex-wrap gap-1.5">{selectedRoles.length ? selectedRoles.map(role => <button key={role.value} type="button" onClick={() => removeRole(role.value)} disabled={role.value === 64 && !canSetDirector} className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-2 py-1 text-[11px] font-extrabold text-slate-700 hover:bg-red-50 hover:text-red-500 disabled:hover:bg-slate-100 disabled:hover:text-slate-700">{role.label}<X size={12} /></button>) : <span className="text-[12px] font-medium text-muted-foreground">Chưa chọn quyền.</span>}</div></div></div></div><div className="flex justify-end gap-3 border-t border-border bg-white px-6 py-4"><button onClick={onClose} className="rounded-xl border border-border px-4 py-2 text-[13px] font-bold hover:bg-muted">Hủy</button><button disabled={submitting} onClick={onSubmit} className="rounded-xl bg-primary px-4 py-2 text-[13px] font-bold text-white disabled:opacity-60">Lưu</button></div></div></div>;
}
function Field({ label, value, error, onChange }: { label: string; value: string; error?: string; onChange: (value: string) => void }) { return <label className="grid gap-1 text-[13px] font-bold text-foreground"><span>{label}</span><input value={value} onChange={e => onChange(e.target.value)} className="h-10 rounded-xl border border-border bg-white px-3 text-[13px] font-medium outline-none focus:border-primary" />{error && <span className="text-[12px] font-medium text-red-500">{error}</span>}</label>; }
