import { X } from 'lucide-react';
import type { HubSummary } from '../types';
import { SearchableSelect } from '../../../../components/ui/SearchableSelect';

export default function AssignUserHubDialog({ open, hubs, value, submitting, onChange, onClose, onSubmit }: { open: boolean; hubs: HubSummary[]; value: string; submitting: boolean; onChange: (value: string) => void; onClose: () => void; onSubmit: () => void }) {
  if (!open) return null;
  const hubOptions = hubs.map(hub => ({ value: String(hub.id), label: [hub.code, hub.name].filter(Boolean).join(' - ') || String(hub.id) }));
  return <div className="fixed inset-0 z-[9999] flex justify-end"><button type="button" aria-label="Đóng" className="fixed inset-0 bg-black/40 backdrop-blur-md animate-in fade-in duration-200" onClick={onClose} /><div className="relative flex h-screen w-full max-w-[560px] flex-col border-l border-border bg-[#f8fafc] shadow-2xl dialog-slide-in"><div className="flex items-center justify-between border-b border-border bg-white px-6 py-4"><h2 className="text-[16px] font-extrabold text-foreground">Gán bưu cục</h2><button onClick={onClose} className="rounded-full p-2 hover:bg-muted"><X size={18} /></button></div><div className="flex-1 overflow-y-auto p-6 custom-scrollbar"><div className="rounded-2xl border border-border bg-white p-4 shadow-sm"><label className="grid gap-2 text-[13px] font-bold text-foreground"><span>Bưu cục</span><SearchableSelect value={value} onValueChange={onChange} options={hubOptions} placeholder={hubs.length ? 'Chọn bưu cục' : 'Không tải được bưu cục'} searchPlaceholder="Tìm bưu cục..." emptyMessage="Không có bưu cục phù hợp." className="h-11 bg-white font-bold text-foreground" disabled={!hubs.length} /></label>{!hubs.length && <p className="mt-2 text-[12px] font-medium text-muted-foreground">API /hubs/active hoặc /hubs chưa trả về danh sách bưu cục.</p>}</div></div><div className="flex justify-end gap-3 border-t border-border bg-white px-6 py-4"><button onClick={onClose} className="rounded-xl border border-border px-4 py-2 text-[13px] font-bold hover:bg-muted">Hủy</button><button disabled={submitting || !value} onClick={onSubmit} className="rounded-xl bg-primary px-4 py-2 text-[13px] font-bold text-white disabled:opacity-60">Gán bưu cục</button></div></div></div>;
}
