import { X } from 'lucide-react';
import { ROLE_BITS } from '../types';
import { SearchableSelect } from '../../../../components/ui/SearchableSelect';

export default function AssignUserRoleDialog({ open, value, canSetDirector, submitting, onChange, onClose, onSubmit }: { open: boolean; value: number; canSetDirector: boolean; submitting: boolean; onChange: (value: number) => void; onClose: () => void; onSubmit: () => void }) {
  if (!open) return null;
  const selectedRoles = ROLE_BITS.filter(role => (value & role.value) !== 0);
  const roleOptions = ROLE_BITS.filter(role => (value & role.value) === 0 && (role.value !== 64 || canSetDirector)).map(role => ({ value: String(role.value), label: role.label }));
  const addRole = (roleValue: string) => { const bit = Number(roleValue); if (bit) onChange(value + bit); };
  const removeRole = (bit: number) => { if (bit === 64 && !canSetDirector) return; onChange(value - bit); };
  return <div className="fixed inset-0 z-[9999] flex justify-end"><button type="button" aria-label="Đóng" className="fixed inset-0 bg-black/40 backdrop-blur-md animate-in fade-in duration-200" onClick={onClose} /><div className="relative flex h-screen w-full max-w-[560px] flex-col border-l border-border bg-[#f8fafc] shadow-2xl dialog-slide-in"><div className="flex items-center justify-between border-b border-border bg-white px-6 py-4"><h2 className="text-[16px] font-extrabold text-foreground">Phân quyền nhân sự</h2><button onClick={onClose} className="rounded-full p-2 hover:bg-muted"><X size={18} /></button></div><div className="flex-1 overflow-y-auto p-6 custom-scrollbar"><div className="rounded-2xl border border-border bg-white p-4 shadow-sm"><div className="mb-3 flex items-center justify-between"><div><div className="text-[13px] font-extrabold text-foreground">Chọn quyền</div><div className="text-[12px] font-medium text-muted-foreground">Role mask tự tính theo quyền đã chọn.</div></div><span className="rounded-full bg-primary/10 px-2 py-1 text-[11px] font-extrabold text-primary">{value}</span></div><SearchableSelect value="" options={roleOptions} onValueChange={addRole} placeholder="Chọn quyền" searchPlaceholder="Tìm quyền..." emptyMessage="Đã chọn tất cả quyền khả dụng." className="h-11 bg-white font-bold text-foreground" /><div className="mt-3 flex flex-wrap gap-1.5">{selectedRoles.length ? selectedRoles.map(role => <button key={role.value} type="button" onClick={() => removeRole(role.value)} disabled={role.value === 64 && !canSetDirector} className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-2 py-1 text-[11px] font-extrabold text-slate-700 hover:bg-red-50 hover:text-red-500 disabled:hover:bg-slate-100 disabled:hover:text-slate-700">{role.label}<X size={12} /></button>) : <span className="text-[12px] font-medium text-muted-foreground">Chưa chọn quyền.</span>}</div></div></div><div className="flex justify-end gap-3 border-t border-border bg-white px-6 py-4"><button onClick={onClose} className="rounded-xl border border-border px-4 py-2 text-[13px] font-bold hover:bg-muted">Hủy</button><button disabled={submitting} onClick={onSubmit} className="rounded-xl bg-primary px-4 py-2 text-[13px] font-bold text-white disabled:opacity-60">Lưu quyền</button></div></div></div>;
}
