-- Import danh sách KH từ Excel (ảnh danh sách warehouse)
-- Chạy SAU: create_customers_table_and_view.sql + add_customers_excel_columns.sql
-- ON CONFLICT (code) DO UPDATE → cập nhật khi chạy lại

INSERT INTO customers (
  code, name, short_name, destination_province, address_hcm, phone_hcm,
  email, contact_person, manager_name, price_table, discount_percent,
  delivery_handler, status, contract_code
) VALUES
  ('KHACHLE', 'Khách lẻ', 'Khách lẻ', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'KHACHLE'),
  ('VIETTEL', 'VIETTEL', 'VIETTEL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'VIETTEL'),
  ('ADO6796', 'A Đô', 'A D6796', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ADO6796'),
  ('ACUU', 'A Cừu', 'A Cừu', NULL, 'Gọi ra lấy', '039 6083720', NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ACUU'),
  ('ADAO', 'A Đào', 'Khách TQ', NULL, '129 Trần Đại Nghĩa, Ấp Tân Kiên, Bình Chánh', '0938 938 112', NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ADAO'),
  ('ADON', 'A Đôn', 'A Đôn', NULL, '52 ĐH 21, Phường Đông Hưng Thuận, Quận 12', '0968 957 771', NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ADON'),
  ('ATANVC', 'A Tân Vận chuyển Trung Việt', 'A Tân Vận chuyển Trung Việt', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ATANVC'),
  ('CMAY', 'C Máy Ác quy', 'C Máy', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'CMAY'),
  ('DATG', 'Đá Thế giới', 'Đá Thế giới', NULL, '18/60, Tăng Nhơn Phú, Phước Long B', '0902 599 917', NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'DATG'),
  ('ADONGECO', 'A Đông ECO', 'A Đông ECO', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ADONGECO'),
  ('ALONG', 'A Long', 'A Long', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ALONG'),
  ('ALUATMT', 'A Luật Mặt Trời', 'A Luật Mặt Trời', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ALUATMT'),
  ('VIETEXPRESS', 'Việt Express', 'Việt Express', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'VIETEXPRESS'),
  ('CTHUY', 'C Thủy', 'C Thủy', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'CTHUY'),
  ('CUONGS9CS', 'Cường S9- Châu Sa', 'Cường S9- Châu Sa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'CUONGS9CS'),
  ('SIMBA', 'SIMBA', 'SIMBA', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'SIMBA'),
  ('ATRUNG', 'A Trung', 'A Trung', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ATRUNG'),
  ('CTRANG81', 'c Trang 81', 'c Trang 81', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'CTRANG81'),
  ('DENLED', 'Đèn led', 'Đèn led', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'DENLED'),
  ('PHUCAN', 'Cty Sơn Phúc An', 'PhucAn', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'PHUCAN'),
  ('THEONE', 'The One', 'The One', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'THEONE'),
  ('TUNGVT', 'Tùng vận tải tàu nhanh', 'Tùng vận tải tàu nhanh', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'TUNGVT'),
  ('AGIAP', 'A Giáp', 'A Giáp', NULL, NULL, '0983 438 479', NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'AGIAP'),
  ('ALONGCTL', 'A Long ( Cao Thắng Long)', 'A Long ( Cao Thắng Long)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ALONGCTL'),
  ('AQUAN48', 'A Quân', 'A Quân - CPN48h', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'ADMIN', 'ACTIVE', 'AQUAN48'),
  ('CUONGS9', 'Cường S9', 'Cường S9', NULL, NULL, '0387 646 874', NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'CUONGS9'),
  ('MADINBD', 'madin Bình Dương', 'madin Bình Dương', 'Bình Dương', 'Số 180 Đường Thống Nhất', '0886 278 778', NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'MADINBD'),
  ('MADINHY', 'Madin Hưng Yên', 'Madin Hưng Yên', 'Hưng Yên', NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'MADINHY'),
  ('NHATTAM', 'Nhất Tâm', 'Nhất Tâm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'NHATTAM'),
  ('QUANGNGAI', 'Quảng Ngãi', 'Quảng Ngãi', 'Quảng Ngãi', NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'QUANGNGAI'),
  ('TAMPHAT', 'Tâm Phát', 'Tâm Phát', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'TAMPHAT'),
  ('VDGROUP', 'VDgroup', 'VDgroup', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'VDGROUP'),
  ('VIPPOSTHN', 'Vippost Hà Nội', 'Vippost Hà Nội', 'Hà Nội', NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'VIPPOSTHN'),
  ('ACESCOHN', 'ACESCO Hà Nội', 'ACESCO Hà Nội', 'Hà Nội', 'Gọi ra lấy', '0934 003 696', NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ACESCOHN'),
  ('ALPHATIC', 'ALPHATIC', 'ALPHATIC', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ALPHATIC'),
  ('CTRANGVC', 'C Trang vận chuyển Trung Việt', 'Chi Trang', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'CTRANGVC'),
  ('HOANGKIM', 'Hoàng Kim-Ninh Hiệp', 'Hoàng Kim-Ninh Hiệp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'HOANGKIM'),
  ('MAXXPOSTHN', 'MAXXPOST Hà Nội', 'MAXXPOST Hà Nội', 'Hà Nội', 'Gọi ra lấy', '0946 691 987', NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'MAXXPOSTHN'),
  ('TOANPHAT', 'Toàn Phát', 'Toàn Phát', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'TOANPHAT'),
  ('VIETTELPT', 'Viettel Phú Thọ', 'Viettel - Phú Thọ', 'Phú Thọ', NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'VIETTELPT'),
  ('DIEPAQ', 'Điệp ắc quy', 'Điệp ắc quy', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'DIEPAQ'),
  ('LOLOTHONG', 'Lộ Lộ Thông', 'Lộ Lộ Thông', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'LOLOTHONG'),
  ('MINHHOANG', 'Minh Hoàng', 'Minh Hoàng', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'MINHHOANG'),
  ('ANAMBT', 'A Nam bãi tập', 'A Nam bãi tập', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ANAMBT'),
  ('PHUCAN2', 'Cty Sơn Phúc An', 'PHUCAN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'PHUCAN2'),
  ('ATL', 'Thắng lợi-A Lương', 'ATL', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ATL'),
  ('TRUNGHIEU', 'Trung Hiếu', 'Trung Hiếu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'TRUNGHIEU'),
  ('ASONCPN', 'A Sơn CPN Toàn Cầu', 'A Sơn CPN Toàn Cầu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ASONCPN'),
  ('CIMAY', 'Chị Mây-kho than', 'Chị Mây-Kho Than', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'CIMAY'),
  ('ADUAN', 'A Duẩn Boamane-Chio', 'A Duẩn Boamane-Chio', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ADUAN'),
  ('ACHIEN', 'A Chiến Loa Bắc Ninh', 'A Chiến Loa Bắc Ninh', 'Bắc Ninh', 'Bình hưng hoà B, Bình Tân', '0902 554 449', NULL, NULL, NULL, NULL, 0, NULL, 'ACTIVE', 'ACHIEN')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  short_name = EXCLUDED.short_name,
  destination_province = EXCLUDED.destination_province,
  address_hcm = EXCLUDED.address_hcm,
  phone_hcm = EXCLUDED.phone_hcm,
  email = EXCLUDED.email,
  contact_person = EXCLUDED.contact_person,
  manager_name = EXCLUDED.manager_name,
  price_table = EXCLUDED.price_table,
  discount_percent = EXCLUDED.discount_percent,
  delivery_handler = EXCLUDED.delivery_handler,
  status = EXCLUDED.status,
  contract_code = EXCLUDED.contract_code,
  updated_at = NOW();

-- Kiểm tra nhanh sau import
-- SELECT code, name, short_name, destination_province, address_hcm, phone_hcm, discount_percent, delivery_handler, status
-- FROM customers WHERE deleted_at IS NULL ORDER BY name;
