import { AlertTriangle, Loader2, X } from 'lucide-react';
import type { InternalCostTrip, TripCostFieldErrors, TripCostFormState } from '../types';

interface Props { trip: InternalCostTrip | null; formState: TripCostFormState; fieldErrors: TripCostFieldErrors; isSubmitting: boolean; error?: string; onClose: () => void; onChange: <K extends keyof TripCostFormState>(key: K, value: TripCostFormState[K]) => void; onSubmit: () => void; }
const fields: Array<{ key: keyof TripCostFormState; label: string }> = [{ key: 'fuel_actual', label: 'fuel_actual' }, { key: 'fuel_cost', label: 'fuel_cost' }, { key: 'other_costs', label: 'other_costs' }];

export default function UpdateTripCostsDialog({ trip, formState, fieldErrors, isSubmitting, error, onClose, onChange, onSubmit }: Props) {
  if (!trip) return null;
  return <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/40 p-4" onClick={onClose}><div className="w-full max-w-lg rounded-2xl border border-border bg-white shadow-2xl" onClick={e => e.stopPropagation()}><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="text-[16px] font-extrabold text-foreground">Cập nhật chi phí chuyến #{trip.id}</h2><p className="mt-1 text-[13px] text-muted-foreground">Chỉ gửi fuel_actual, fuel_cost, other_costs.</p></div><button onClick={onClose} className="rounded-lg p-2 text-muted-foreground hover:bg-muted"><X size={18} /></button></div><div className="space-y-3 p-5">{fields.map(field => <label key={field.key} className="block"><span className="text-[12px] font-bold text-muted-foreground">{field.label}</span><input type="number" min="0" value={formState[field.key]} onChange={e => onChange(field.key, e.target.value)} className="mt-1 h-10 w-full rounded-xl border border-border bg-muted/5 px-3 text-[13px] font-medium focus:outline-none focus:ring-2 focus:ring-primary/10" />{fieldErrors[field.key] && <span className="mt-1 block text-[12px] font-medium text-red-500">{fieldErrors[field.key]}</span>}</label>)}{error && <div className="flex items-center gap-2 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-[13px] font-medium text-amber-800"><AlertTriangle size={15} />{error}</div>}</div><div className="flex justify-end gap-2 border-t border-border px-5 py-4"><button onClick={onClose} disabled={isSubmitting} className="h-10 rounded-xl border border-border bg-white px-4 text-[13px] font-bold text-muted-foreground hover:bg-muted disabled:opacity-60">Đóng</button><button onClick={onSubmit} disabled={isSubmitting} className="h-10 rounded-xl bg-primary px-4 text-[13px] font-bold text-white hover:bg-primary/90 disabled:opacity-60">{isSubmitting ? <Loader2 className="animate-spin" size={16} /> : 'Cập nhật'}</button></div></div></div>;
}
