import { Loader2, X } from 'lucide-react';
import type { AssignDriverHandoverFormState, TripSummary, UserSummary, WaybillHandoverItem } from '../types';

interface Props { isOpen: boolean; waybill: WaybillHandoverItem | null; drivers: UserSummary[]; trips: TripSummary[]; formState: AssignDriverHandoverFormState; error: string; isSubmitting: boolean; onChange: <K extends keyof AssignDriverHandoverFormState>(key: K, value: AssignDriverHandoverFormState[K]) => void; onSubmit: () => void; onClose: () => void }
const driverName = (driver: UserSummary) => [driver.name || driver.username, driver.phone].filter(Boolean).join(' · ');

export default function AssignDriverHandoverDialog({ isOpen, waybill, drivers, trips, formState, error, isSubmitting, onChange, onSubmit, onClose }: Props) {
  if (!isOpen || !waybill) return null;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><div className="w-full max-w-lg overflow-hidden rounded-2xl bg-white shadow-xl"><div className="flex items-center justify-between border-b border-border px-5 py-4"><div><p className="text-[12px] font-bold uppercase tracking-wider text-primary">Bàn giao tài xế</p><h2 className="text-lg font-black text-foreground">{waybill.waybill_code}</h2></div><button onClick={onClose} className="flex h-9 w-9 items-center justify-center rounded-lg hover:bg-muted"><X size={18} /></button></div><div className="space-y-4 p-5">{error && <div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-[13px] font-bold text-red-700">{error}</div>}<label><span className="mb-2 block text-[12px] font-bold text-foreground">Tài xế</span><select value={formState.driver_id} onChange={event => onChange('driver_id', event.target.value)} className="h-11 w-full rounded-xl border border-border bg-white px-3 text-[13px] font-bold outline-none focus:ring-2 focus:ring-primary/10"><option value="">Chọn tài xế</option>{drivers.map(driver => <option key={driver.id} value={driver.id}>{driverName(driver)}</option>)}</select></label><label><span className="mb-2 block text-[12px] font-bold text-foreground">Chuyến xe liên quan</span><select value={formState.trip_id} onChange={event => onChange('trip_id', event.target.value)} className="h-11 w-full rounded-xl border border-border bg-white px-3 text-[13px] font-bold outline-none focus:ring-2 focus:ring-primary/10"><option value="">Không gắn chuyến</option>{trips.map(trip => <option key={trip.id} value={trip.id}>Chuyến #{trip.id}{trip.status ? ` · ${trip.status}` : ''}</option>)}</select></label><div className="flex justify-end gap-2"><button onClick={onClose} className="h-10 rounded-lg border border-border px-4 text-[13px] font-bold text-muted-foreground hover:bg-muted">Hủy</button><button onClick={onSubmit} disabled={isSubmitting || !formState.driver_id} className="flex h-10 items-center gap-2 rounded-lg bg-primary px-4 text-[13px] font-bold text-white hover:bg-primary/90 disabled:opacity-60">{isSubmitting && <Loader2 size={15} className="animate-spin" />} Tiếp tục</button></div></div></div></div>;
}
