import { X } from 'lucide-react';
import type { ReactNode } from 'react';
import type { CodWaybillDetail } from '../types';
interface Props { waybill: CodWaybillDetail | null; onClose: () => void; formatHub: (id?: string | number | null) => string; renderStatus: (status?: string | null) => ReactNode; renderPayment: (payment?: string | null) => ReactNode }
const display = (value: unknown, suffix = '') => value === null || value === undefined || value === '' ? '—' : `${value}${suffix}`;
export default function CodWaybillDetailDialog({ waybill, onClose, formatHub, renderStatus, renderPayment }: Props) {
  if (!waybill) return null;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><div className="w-full max-w-2xl overflow-hidden rounded-2xl border border-border bg-white shadow-xl"><div className="flex items-center justify-between border-b border-border px-4 py-3"><div><p className="text-[11px] font-black uppercase tracking-wider text-primary">Chi tiết COD & cước CC</p><h2 className="text-base font-black text-foreground">{waybill.waybill_code}</h2></div><button onClick={onClose} className="rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-foreground"><X size={18} /></button></div><div className="grid max-h-[70vh] gap-3 overflow-y-auto p-4 text-[13px] md:grid-cols-2 custom-scrollbar"><Info label="Người gửi" value={display(waybill.sender_info)} /><Info label="Người nhận" value={display(waybill.receiver_info)} /><Info label="Hub đi" value={formatHub(waybill.origin_hub_id)} /><Info label="Hub đến" value={formatHub(waybill.dest_hub_id)} /><Info label="Trạng thái" value={renderStatus(waybill.current_state)} /><Info label="Loại thanh toán" value={renderPayment(waybill.payment_type)} /><Info label="Cước phí" value={display(waybill.cost_amount)} /><Info label="Cân nặng" value={display(waybill.weight, ' kg')} /><Info label="Kích thước" value={`${display(waybill.length)} × ${display(waybill.width)} × ${display(waybill.height)} cm`} /><Info label="Trọng lượng quy đổi" value={display(waybill.volumetric_weight, ' kg')} /></div></div></div>;
}
function Info({ label, value }: { label: string; value: ReactNode }) { return <div className="rounded-xl border border-border bg-muted/10 p-3"><div className="text-[11px] font-bold uppercase tracking-wider text-muted-foreground">{label}</div><div className="mt-1 font-bold text-foreground break-words">{value}</div></div>; }
