export enum WaybillStatus {
  RECEIVED = 'RECEIVED',
  IN_WAREHOUSE = 'IN_WAREHOUSE',
  MANIFEST_CLOSED = 'MANIFEST_CLOSED',
  IN_TRANSIT = 'IN_TRANSIT',
  AT_DEST_HUB = 'AT_DEST_HUB',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  RETURNED = 'RETURNED',
  CANCELLED = 'CANCELLED',
}

export enum WaybillPriority {
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}
